<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/*
|--------------------------------------------------------------------------
| Register REST route
|--------------------------------------------------------------------------
*/

add_action( 'rest_api_init', function() {
	register_rest_route(
		'gfsf/v1',
		'/relay',
		array(
			'methods'             => 'POST',
			'callback'            => 'gfsf_relay_webhook',
			'permission_callback' => 'gfsf_verify_relay_request',
		)
	);
} );

/*
|--------------------------------------------------------------------------
| Send packet to local WP relay
|--------------------------------------------------------------------------
*/

function gfsf_send_webhook( $webhook_url, $payload, $entry, $form ) {

	$relay_url = rest_url( 'gfsf/v1/relay' );

	$request_body = array(
		'entry_id'              => rgar( $entry, 'id' ),
		'form_id'               => rgar( $form, 'id' ),
		'salesforce_webhook_url'=> $webhook_url,
		'payload'               => $payload,
	);
	$encoded_body = wp_json_encode( $request_body );
	$relay_token  = hash_hmac( 'sha256', $encoded_body, wp_salt( 'auth' ) );

	$response = wp_remote_post(
		$relay_url,
		array(
			'method'   => 'POST',
			'timeout'  => 0.01,
			'blocking' => false,
			'headers'  => array(
				'Content-Type' => 'application/json',
				'X-GFSF-Relay-Token' => $relay_token,
			),
			'body'     => $encoded_body,
		)
	);

	if ( is_wp_error( $response ) ) {
		GFAPI::add_note(
			rgar( $entry, 'id' ),
			0,
			'GF SF Webhook',
			'❌ Payload delivery failed: ' . $response->get_error_message()
		);
		return;
	}

	GFAPI::add_note(
		rgar( $entry, 'id' ),
		0,
		'GF SF Webhook',
		'✅ Payload sent.'
	);
}

/**
 * Confirms that relay requests were generated by this WordPress installation.
 *
 * @param WP_REST_Request $request Relay request.
 * @return bool
 */
function gfsf_verify_relay_request( WP_REST_Request $request ) {
	$provided_token = trim( (string) $request->get_header( 'X-GFSF-Relay-Token' ) );

	if ( '' === $provided_token ) {
		return false;
	}

	$expected_token = hash_hmac( 'sha256', $request->get_body(), wp_salt( 'auth' ) );

	return hash_equals( $expected_token, $provided_token );
}

/*
|--------------------------------------------------------------------------
| Relay callback
|--------------------------------------------------------------------------
*/

function gfsf_relay_webhook( WP_REST_Request $request ) {

	$data                  = $request->get_json_params();
	$entry_id              = isset( $data['entry_id'] ) ? absint( $data['entry_id'] ) : 0;
	$form_id               = isset( $data['form_id'] ) ? absint( $data['form_id'] ) : 0;
	$salesforce_webhook_url = isset( $data['salesforce_webhook_url'] ) ? esc_url_raw( trim( (string) $data['salesforce_webhook_url'] ) ) : '';
	$payload               = isset( $data['payload'] ) ? $data['payload'] : array();

	if ( $entry_id < 1 || $form_id < 1 || '' === $salesforce_webhook_url || ! wp_http_validate_url( $salesforce_webhook_url ) || empty( $payload ) ) {
		if ( $entry_id ) {
			GFAPI::add_note(
				$entry_id,
				0,
				'GF SF Webhook',
				'❌ Payload rejected: missing entry_id, form_id, webhook URL, or payload.'
			);
		}

		return new WP_REST_Response(
			array(
				'success' => false,
				'message' => 'Missing required relay data.',
			),
			400
		);
	}

	$response = wp_remote_post(
		$salesforce_webhook_url,
		array(
			'method'  => 'POST',
			'timeout' => 20,
			'headers' => array(
				'Content-Type' => 'application/json',
			),
			'body'    => wp_json_encode( $payload ),
		)
	);

	if ( is_wp_error( $response ) ) {
		GFAPI::add_note(
			$entry_id,
			0,
			'GF SF Webhook',
			'❌ Payload rejected: ' . $response->get_error_message()
		);

		return new WP_REST_Response(
			array(
				'success' => false,
				'message' => $response->get_error_message(),
			),
			500
		);
	}

	$code = wp_remote_retrieve_response_code( $response );
	$body = wp_remote_retrieve_body( $response );

	if ( $code >= 200 && $code < 300 ) {
		GFAPI::add_note(
			$entry_id,
			0,
			'GF SF Webhook',
			'✅ Payload delivery success. HTTP ' . $code
		);
	} else {
		GFAPI::add_note(
			$entry_id,
			0,
			'GF SF Webhook',
			"❌ Webhook returned HTTP {$code}.\n\n{$body}"
		);
	}

	return new WP_REST_Response(
		array(
			'success' => ( $code >= 200 && $code < 300 ),
			'code'    => $code,
			'body'    => $body,
		),
		$code
	);
}
